import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
    pedantic: "warn",
    perf: "warn",
    restriction: "warn",
    style: "warn",
    suspicious: "warn",
  },
  env: {
    builtin: true,
  },
  ignorePatterns: ["dist/", ".output/", "node_modules/"],
  jsPlugins: ["eslint-plugin-solid"],
  options: {
    typeAware: true,
  },
  overrides: [
    {
      files: ["*.tsx", "*.jsx"],
      rules: {
        "typescript/prefer-readonly-parameter-types": "off",
        "typescript/strict-void-return": "off",
        "unicorn/filename-case": ["warn", { case: "pascalCase" }],
      },
    },
  ],
  rules: {
    "oxc/no-optional-chaining": "off",
    "eslint/sort-imports": "off",
    "eslint/no-plusplus": "off",
    "eslint/no-undefined": "off",
    "eslint/max-statements": "off",
    "eslint/func-style": ["warn", "declaration", { allowArrowFunctions: true }],
    "eslint/id-length": "off",
    "eslint/no-ternary": "off",
    "eslint/max-lines-per-function": "off",
    "eslint/no-magic-numbers": "off",
    "eslint/max-lines": "off",
    "eslint/sort-keys": "off",
    "typescript/strict-boolean-expressions": "off",
    "typescript/promise-function-async": "off",
    "unicorn/no-null": "off",
    "unicorn/prefer-node-protocol": "off",
    "unicorn/prefer-ternary": "off",
    "unicorn/prefer-number-coercion": "off",
    "unicorn/filename-case": ["warn", { case: "camelCase" }],
    "solid/components-return-once": "error",
    "solid/imports": "error",
    "solid/jsx-no-duplicate-props": "error",
    "solid/jsx-no-undef": "error",
    "solid/no-destructure": "error",
    "solid/no-innerhtml": "error",
    "solid/no-react-deps": "error",
    "solid/no-react-specific-props": "error",
    "solid/prefer-for": "warn",
    "solid/prefer-show": "warn",
    "solid/reactivity": "error",
    "solid/self-closing-comp": "warn",
    "solid/style-prop": "error",
  },
});
