name: Release

on:
  push:
    branches: [main]
    paths:
      - "packages/solid-md3/**"
      - "package.json"
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Bun and dependencies
        uses: ./.github/actions/setup-bun
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          publish: bun run publish
          version: bun run version
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
